Тема “Вычисления с помощью Numpy”

In [ ]:
import numpy as np

Задание 1

In [ ]:
b = np.array([[1, 2, 3, 3, 1],[6, 8, 11, 10, 7]])

In [4]:
a = b.T

In [6]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [17]:
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

Задание 2

In [21]:
a_centered = a - mean_a
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

Задание 3

In [50]:
a_centered_sp = a_centered[:5,0].dot(a_centered[:5,1])
a_centered_sp

8.0

In [51]:
n1 = a.shape[0] - 1
a_centered_sp/n1

2.0

Задание 4

In [53]:
np.cov(b)[0,1]

2.0